# Generated by Django 2.2 on 2019-05-03 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monAsso', '0002_asso_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asso',
            name='user',
            field=models.OneToOneField(on_delete='models.CASCADE', related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
