# Generated by Django 2.2 on 2019-05-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monAsso', '0003_auto_20190503_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asso',
            name='user',
        ),
    ]
