# Generated by Django 2.2 on 2019-05-03 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monAsso', '0004_remove_asso_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='asso',
            name='nomResponsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
