# Generated by Django 2.2 on 2019-05-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monAsso', '0005_asso_nomresponsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asso',
            old_name='nomResponsable',
            new_name='userResponsable',
        ),
    ]
