# Generated by Django 2.2 on 2019-05-03 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monAsso', '0006_auto_20190503_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benevole',
            fields=[
                ('idBenevole', models.AutoField(primary_key=True, serialize=False)),
                ('userResponsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
