# Generated by Django 2.2 on 2019-05-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monAsso', '0007_benevole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benevole',
            options={'ordering': ['idBenevole'], 'verbose_name': 'Benevole'},
        ),
    ]
