# Generated by Django 2.2 on 2019-05-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monAsso', '0008_auto_20190503_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='nomBenevole',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
