# Generated by Django 2.2 on 2019-05-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monAsso', '0009_benevole_nombenevole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benevole',
            name='nomBenevole',
        ),
    ]
