# Generated by Django 2.2 on 2019-05-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monAsso', '0010_remove_benevole_nombenevole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('idEvent', models.AutoField(primary_key=True, serialize=False)),
                ('nomEvent', models.CharField(max_length=30)),
                ('lieu', models.CharField(max_length=30)),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('nbBenevole', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'evenement',
                'ordering': ['idEvent'],
            },
        ),
    ]
